### PR TITLE
make importing easier. does this work?

### PR DESCRIPTION
**Pull request by jessitron**

### CODE REVIEW

**Comment by ddgenome** [comment]
What issue are you trying to solve here?

**Comment by jessitron** [comment]
this is an improvement, I'm gonna merge it. we can change it later if there's even better ways

**Comment by cdupuis** [comment]
Apparently exported types from an index.js can be imported with just `@atomist/slack-messages`.

**Comment by jessitron** [comment]
yes, and the docs were doing that, (slack messages page in the refresh branch) so rather than correct it I made it work

**Comment by ddgenome** [comment]
Even better way to what?

**Comment by ddgenome** [comment]
What docs?

**Comment by jessitron** [comment]
sorry dd, did not see your comment before i came back to merge. should have hit refresh

**Comment by ddgenome** [comment]
Now that you have seen it can you answer it? I'm still not sure what problem this solves.

**Comment by jessitron** [comment]
> what docs:
the example in 
http://127.0.0.1:8000/automations/slack/#rich-messages
... if you're running the refresh branch.

**Comment by cdupuis** [comment]
it allows to you to do

`import { SlackMessage } from "@atomist/slack-messages"` instead of 
`import { SlackMessage } from "@atomist/slack-messages/SlackMessage"`

**Comment by ddgenome** [comment]
If we wanted to offer that, which I'm not sure is actually a good idea, why would would only do it for SlackMessages? Why not RugMessages and Markdown too?

**Pull request merged**
